//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedLabProj.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int ID { get; set; }
        public int PriceListID { get; set; }
        public System.TimeSpan TimeOf { get; set; }
        public System.DateTime DateOf { get; set; }
        public int PatientID { get; set; }
        public int MedicalWorkerID { get; set; }
    
        public virtual MedicalWorker MedicalWorker { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual PriceList PriceList { get; set; }
    }
}
